// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "apple":return img`
. . . . . . . e c 7 . . . . . . 
. . . . e e e c 7 7 e e . . . . 
. . c e e e e c 7 e 2 2 e e . . 
. c e e e e e c 6 e e 2 2 2 e . 
. c e e e 2 e c c 2 4 5 4 2 e . 
c e e e 2 2 2 2 2 2 4 5 5 2 2 e 
c e e 2 2 2 2 2 2 2 2 4 4 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 2 2 e 
c e e 2 2 2 2 2 2 2 2 2 2 4 2 e 
. e e e 2 2 2 2 2 2 2 2 2 4 e . 
. 2 e e 2 2 2 2 2 2 2 2 4 2 e . 
. . 2 e e 2 2 2 2 2 4 4 2 e . . 
. . . 2 2 e e 4 4 4 2 e e . . . 
. . . . . 2 2 e e e e . . . . . 
`;
            case "image1":
            case "playerMain":return img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "enemy":return img`
. . . . f f f f f f f f . . . . 
. . . f 4 e e e e e e e f . . . 
. f f f e e e e e e e e f f f . 
f 4 4 f e e e e e e e e f e e f 
f e e e e e e e e e e e e e e f 
. f f f f f f f f f f f f f f . 
. . . f d f d d d d f d f . . . 
. . . f d f d f d d f d f . . . 
. . . f d d f d f d d d f . . . 
. f . . f f f f f f f f . . . . 
f d f f f 4 4 2 2 2 2 2 f f . . 
f d f 4 2 2 2 2 2 2 2 2 2 2 f . 
. f f f f 2 2 2 2 2 2 2 f f f . 
. . . . f f f f f f f f f d d f 
. . . . f 8 6 f f 8 6 f . f f . 
. . . . . f f . . f f . . . . . 
`;
            case "image3":
            case "emerald":return img`
8 . . . . . . . . . . . . . . 8 
. 8 . . 8 f f f f f f f . . 8 . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. 8 . . f f f f f f f f . . 8 . 
8 . . . . . . . . . . . . . . 8 
`;
            case "image5":
            case "projectile":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . f f f f f f f f f f f . . . 
. . . f 6 6 6 6 6 6 6 6 6 f . . 
. . . . f 8 8 9 9 9 9 9 9 6 f . 
. . . f 6 6 6 6 6 6 6 6 6 f . . 
. . f f f f f f f f f f f . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "projectileAdd":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . 7 7 . . 
. . . . . . . . . . . . 7 7 . . 
. f f f f f f f f f 7 7 7 7 7 7 
. . f 6 6 6 6 6 6 6 7 7 7 7 7 7 
. . . f 8 8 9 9 9 9 9 9 7 7 . . 
. . f 6 6 6 6 6 6 6 6 6 7 7 . . 
. f f f f f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "fadeNext":
            case "anim1":return [img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f f f f . . . . . . . . . . 
f f f f f f . . . . . . . . . . 
f f f f f f . . . . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f f f f f f f . . . . . . . 
f f f f f f f f f . . . . . . . 
f f f f f f f f f . . . . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f f f f f f f f f f . . . . 
f f f f f f f f f f f f . . . . 
f f f f f f f f f f f f . . . . 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . . . . 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . . . . f f f f f f 
f f f . . . . . . . f f f f f f 
f f f . . . . . . . f f f f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f . . . . f f f f f f f f f 
f f f . . . . f f f f f f f f f 
f f f . . . . f f f f f f f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f . . . . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . . . . f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f . . . . f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f . . f f f f f f f 
f f f f f f f . . f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`, img`
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
`];
            case "eating":
            case "anim2":return [img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . 8 7 . f d f d f d f . . . . 
. 8 7 . . f d d d d d f . . . . 
f 8 6 f . . f f f f f . . . . . 
2 2 4 5 f f e 2 2 2 2 f f f f . 
2 2 2 4 f 2 2 2 2 2 2 2 2 2 2 f 
f 2 2 f f f 2 2 2 2 2 f f f 2 f 
. f f . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . 8 7 d f d f d f . . . . 
. . . 8 7 f d f d f d f . . . . 
. . f 8 6 f d d d d d f . . . . 
. f 2 2 4 5 f f f f f . . . . . 
. f 2 2 2 4 f 2 2 2 2 f f f f . 
. . f 2 2 f 2 2 2 2 2 2 2 2 2 f 
. . . f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . 8 7 d f d f d f . . . . 
. . . 8 7 f d f d f d f . . . . 
. . f 8 6 f d d d d d f . . . . 
. f 2 2 f . f f f f f . . . . . 
. f 2 2 2 f f 2 2 2 2 f f f f . 
. . f 2 2 f 2 2 2 2 2 2 2 2 2 f 
. . . f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . 8 7 d f d f d f . . . . 
. . . 8 7 f d f d f d f . . . . 
. . f 8 6 f d d d d d f . . . . 
. f 2 f . . f f f f f . . . . . 
. f 2 f . f f 2 2 2 2 f f f f . 
. . f 2 f f 2 2 2 2 2 2 2 2 2 f 
. . . f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . 8 7 d f d f d f . . . . 
. . . 8 7 f d f d f d f . . . . 
. . f 8 6 f d d d d d f . . . . 
. f d f . . f f f f f . . . . . 
. f f f f f f 2 2 2 2 f f f f . 
. f 2 2 2 f 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. 8 7 . . f f f f f f f . f d f 
8 7 . . . f 8 6 f f 8 6 . . f . 
8 6 . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "walking":
            case "anim3":return [img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . 6 8 f f 6 8 f . . f . 
. . . . . f f . . f f . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "shine":
            case "anim4":return [img`
8 . . . . . . . . . . . . . . 8 
. 8 . . 8 f f f f f f f . . 8 . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. 8 . . f f f f f f f f . . 8 . 
8 . . . . . . . . . . . . . . 8 
`, img`
. . . . . . . . . . . . . . . . 
. 8 . . 8 f f f f f f f . . 8 . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. 8 . . f f f f f f f f . . 8 . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . 8 f f f f f f f . . . . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. . . . f f f f f f f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. 8 . . 8 f f f f f f f . . 8 . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. 8 . . f f f f f f f f . . 8 . 
. . . . . . . . . . . . . . . . 
`, img`
8 . . . . . . . . . . . . . . 8 
. 8 . . 8 f f f f f f f . . 8 . 
. . . 8 6 7 7 7 7 7 7 7 e . . . 
. . 8 8 7 8 f f f f f 7 e e . . 
. f 7 7 8 6 7 7 7 7 7 e 7 7 e . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 f 7 f . 
. f 7 f 7 7 7 7 7 7 7 7 e 7 f . 
. f 7 7 f 7 7 7 7 7 7 e 7 7 f . 
. . f f 7 f f f f f f 7 e e . . 
. . . f 7 7 7 7 7 7 7 7 e . . . 
. 8 . . f f f f f f f f . . 8 . 
8 . . . . . . . . . . . . . . 8 
`];
            case "projectileAddAnim":
            case "anim5":return [img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. 8 8 8 . f d d d d d f . . . . 
8 6 8 . . . f f f f f . . . . . 
. 8 8 8 f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. 8 8 8 . f d d d d d f . . . . 
8 6 8 . . . f f f f f . . . . . 
. 8 8 8 f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. 8 8 8 . f d f d f d f . . . . 
8 6 8 . . f d d d d d f . . . . 
. 8 8 8 . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. . f f 2 2 2 2 2 2 2 2 2 2 2 f 
. . . . f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. 8 8 8 . f d d d d d f . . . . 
8 6 8 . . . f f f f f . . . . . 
. 8 8 8 f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "projectileThrow":
            case "anim6":return [img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. 8 8 8 . f d d d d d f . . . . 
8 6 8 . . . f f f f f . . . . . 
. 8 8 8 f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. 8 8 8 . . f f f f f . . . . . 
8 6 8 f f f e 2 2 2 2 f f f f . 
. 8 8 8 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . . . . . f f f f f . . . . . 
. . . . f f e 2 2 2 2 f f f f . 
. . . . f d f 8 2 2 2 2 2 2 2 f 
. . . . f d f 6 8 2 2 f f f 2 f 
. . . . f f 8 8 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f 8 8 8 . f d f 
. . . . . f 8 6 f f 8 6 8 . f . 
. . . . . . f f . 8 8 8 . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 8 8 8 . 
. . . . . . f f . . f f . 8 6 8 
. . . . . . . . . . . . 8 8 8 . 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . 8 8 8 
. . . . . . . . . . . . . . 8 6 
`, img`
. . . . . f f f f f f f . . . . 
. . . . f e e 2 2 2 2 2 f . . . 
. . . . f e 2 2 2 2 2 2 f . . . 
. . f f f f f f f f f f f . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d f d f d f . . . . 
. . . . . f d d d d d f . . . . 
. . f . . . f f f f f . . . . . 
. f d f f f e 2 2 2 2 f f f f . 
. f d f 2 2 2 2 2 2 2 2 2 2 2 f 
. . f f f f 2 2 2 2 2 f f f 2 f 
. . . . . f 2 2 2 2 2 f . f f f 
. . . . . f f f f f f f . f d f 
. . . . . f 8 6 f f 8 6 . . f . 
. . . . . . f f . . f f . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
